### ISSUE TITLE
The OpenBSD displays `?` when using vtop.

### ISSUE THREAD

**Issue by NanXiao** [MrRio/vtop#120]
Hi vtop owner,

Greeting from me!

My OS is `OpenBSD`, and SSH client is `Cygwin`. The `vtop` displays `?`:
![capture](https://user-images.githubusercontent.com/2338189/39108485-14ace104-46fb-11e8-90f7-8e8f1e288674.JPG)

Is it normal? Or there are issues with `vtop`/`nodejs`/`Cygwin`/`OpenBSD`?

Thanks in advance!

Best Regards
Nan Xiao

**Comment by Eeems** [comment]
You may want to check your character set/font.

**Comment by NanXiao** [comment]
@Eeems 

Thanks for your reply! Changing `LC_CTYPE` to `en_US.UTF-8` (Add "export LC_CTYPE=en_US.UTF-8" in  `~/.profile`) fix this issue.

Best Regards
Nan Xiao
