### ISSUE TITLE
vtop consumes processor's time 

### ISSUE THREAD

**Issue by ghost** [MrRio/vtop#55]
hi 
first, I want to think you for the project, I find it cool :)
But I have a little problem, I don't if you too have the same problem, vtop uses processor more than htop, as you can see on the picture, 51% vs 3%
 ![screenshot vtop vs htop](http://picpaste.com/pics/JKYAMnun.1420108869.png)

**Comment by babhishek21** [comment]
Of course it does. `vtop` runs on NodeJS. You can expect such resource usages. That said **51%** seems a bit too much.

**Comment by MrRio** [comment]
Yeah 51% suggests a problem. There's certainly something we can improve

**Comment by rimolive** [comment]
Please check my comment in issue #82. It seems an easy fix but before send the PR I'd like your thoughts.
