### ISSUE TITLE
Option to disable automatic updates

### ISSUE THREAD

**Issue by liamnewmarch** [MrRio/vtop#59]
Great work with vtop, I’ve used it on loads of machines in a variety of places.

I’m currently trying to use it on a server’s mission-control style dashboard, however I’m having difficulty running it longterm because autoupdate keeps dropping to a sudo password prompt.

For now I’ve commented out part of the source to disable automatic updating, but it would be great if there was a flag to do this without me hacking around.  Maybe `vtop --no-update` or something?

**Comment by tomisme** [comment]
I've also done the same, vtop keeps requesting an upgrade even after updating. Also, I install my global npm packages in ~/.npm so that they don't require sudo to update.

**Comment by neilpanchal** [comment]
I second this. Automatic updates are crashing vtop despite of updating it through vtop and it is running the latest release. 

Automatic updates should be turned off by default in my opinion.

**Comment by derhuerst** [comment]
I think subtly informing that there is an update is okay, anything else is limiting the users.
