### ISSUE TITLE
vtop not in path

### ISSUE THREAD

**Issue by miltonio94** [MrRio/vtop#68]
I try running vtop after installing it, but I  get the 'command not found' error
<img width="1474" alt="screen shot 2016-05-20 at 12 41 53" src="https://cloud.githubusercontent.com/assets/8180004/15426762/8212b82e-1e88-11e6-8f5a-6f7526d4e0aa.png">

**Comment by derhuerst** [comment]
As npm says, it symlinked the `vtop` executable into `/usr/local/Cellar/node/5.10.1/bin`. Is that in your `$PATH`?

**Comment by miltonio94** [comment]
it is now, and it's working now
