### ISSUE TITLE
vtop doesn't remember selected theme

### ISSUE THREAD

**Issue by VladimirDev93** [MrRio/vtop#96]
If I change the theme ``vtop --theme monokai`` for example, it doesn't remember the theme if I open vtop again. If I want to open ``vtop`` with specific theme, i have to type the command every time. Can you make it to remember the user selected theme?

Oh yeah, the ``vtop --theme [name]`` works properly, it's just I have to type this every time when I'm about to start the application.

``Ùbuntu 16.04 x64``,
``nodejs --version: 8.1.2``,
``npm --version: 5.0.3``

or

can I just replace the ``${themeName}`` in 
```javascript
for (var i = 0; i < files.length; i++) {
    let themeName = files[i].replace(path.join(__dirname, 'themes') + path.sep, '').replace('.json', '')
    themes += `${themeName}|`
  }
```
with the preferred theme?

EDIT:

Nevermind, found the solution. Changed from (app.js : 405):
```javascript
loadedTheme = require(`./themes/${theme}.json`)
```
to:
```javascript
loadedTheme = require(`./themes/monokai.json`)
```

**Comment by caseybrichardson** [comment]
Since you're on Ubuntu the simpler solution is available in the README:

> You could add this to your aliases if you'd like to use it always.
> `alias vtop="vtop --theme brew"`

**Comment by VladimirDev93** [comment]
Omg, I didn't even read that part. Thanks @caseybrichardson, kudos.
